# Generated by Django 5.2.1 on 2025-06-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='Music_path',
        ),
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
