# Generated by Django 5.2.1 on 2025-06-05 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_album_song_alter_music_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='song_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(upload_to='music/'),
        ),
    ]
