# Generated by Django 5.2.1 on 2025-06-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_music_song_album_alter_music_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
