# Generated by Django 5.2.1 on 2025-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_music_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSessionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('seconds_used', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
