# Generated by Django 5.2.1 on 2025-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_anonymoussessionusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='music_album_covers/'),
        ),
    ]
