// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtxNr_XcX_vI4JzWU20bucuiDRVip5a98',
    appId: '1:525460766044:web:37ac46845454ab34d71599',
    messagingSenderId: '525460766044',
    projectId: 'musicappflutter-87ed5',
    authDomain: 'musicappflutter-87ed5.firebaseapp.com',
    storageBucket: 'musicappflutter-87ed5.firebasestorage.app',
    measurementId: 'G-W8R1HKYHCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcuMH6dPDWSxCH8pCtOo4qWm1QMhPpKGM',
    appId: '1:525460766044:android:a96937423ac5812ed71599',
    messagingSenderId: '525460766044',
    projectId: 'musicappflutter-87ed5',
    storageBucket: 'musicappflutter-87ed5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrCoW2PHhvQYRa5uGz_kMPyqmFr0l3WhA',
    appId: '1:525460766044:ios:62edb9a175ea05c6d71599',
    messagingSenderId: '525460766044',
    projectId: 'musicappflutter-87ed5',
    storageBucket: 'musicappflutter-87ed5.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrCoW2PHhvQYRa5uGz_kMPyqmFr0l3WhA',
    appId: '1:525460766044:ios:62edb9a175ea05c6d71599',
    messagingSenderId: '525460766044',
    projectId: 'musicappflutter-87ed5',
    storageBucket: 'musicappflutter-87ed5.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtxNr_XcX_vI4JzWU20bucuiDRVip5a98',
    appId: '1:525460766044:web:7333fbb983632d0ed71599',
    messagingSenderId: '525460766044',
    projectId: 'musicappflutter-87ed5',
    authDomain: 'musicappflutter-87ed5.firebaseapp.com',
    storageBucket: 'musicappflutter-87ed5.firebasestorage.app',
    measurementId: 'G-X3SSLZZTN0',
  );
}
